cloudinary/cloudinary-cli

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/utils.py
[x] New feature
[ ] Bug fix
[ ] Yes
[x] No
> Add support for `--keep-unique` option in `sync`

- cloudinary_cli/utils/api_utils.py
Fixes #26
[ ] New feature
[x] Bug fix
[ ] Yes
[x] No
> Fix `sync --pull` for root folder

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/api_utils.py
[x] New feature
[ ] Bug fix
[ ] Yes
[x] No
> Add `deletion-batch-size` option to `sync`

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/file_utils.py
- test/test_file_utils.py
[x] New feature
[ ] Bug fix
[x] Yes
[ ] No
> Add `include-hidden` option to `sync`

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/config_utils.py
- cloudinary_cli/utils/file_utils.py
- cloudinary_cli/utils/json_utils.py
- cloudinary_cli/utils/utils.py
[ ] New feature
[x] Bug fix
[ ] Yes
[x] No
> Improve sync of files with special characters

- cloudinary_cli/core/admin.py
- cloudinary_cli/core/search.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/utils.py
- test/test_utils.py
Enable auto-paginated Admin API calls using the `-A`/`--auto_paginate` flag
> Enable auto-paginated Admin API calls

- cloudinary_cli/utils/utils.py
- test/test_utils.py
Fix issue when passing optional arguments as positional
[ ] New feature
[x] Bug fix
[x] Yes
[ ] No
> Fix issue with optional arguments

- cloudinary_cli/modules/migrate.py
> Fix `migrate` command

- cloudinary_cli/utils/api_utils.py
> Fix `sync` of private assets

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/file_utils.py
- test/test_file_utils.py
> Fix `sync` file extension normalization

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/api_utils.py
> Fix syncing of the raw files with uppercase extension

- cloudinary_cli/cli.py
- cloudinary_cli/modules/sync.py
- cloudinary_cli/modules/upload_dir.py
- cloudinary_cli/utils/api_utils.py
> Improve `sync` error handling

- cloudinary_cli/utils/utils.py
> Remove internal methods from help strings

- cloudinary_cli/utils/utils.py
- test/test_utils.py
> Fix integer parameters handling

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/file_utils.py
> Fix `sync` on Windows

- cloudinary_cli/cli.py
> Fix deprecation warning

- cloudinary_cli/cli.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/config_utils.py
- cloudinary_cli/utils/utils.py
- test/test_cli_config.py
> Improve error handling of missing configuration

- cloudinary_cli/utils/utils.py
> Sort commands in help strings

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/utils.py
- test/test_utils.py
This is our famous `sync` functionality. 
Please approve that the code is readable.
The code is easier to see in a file:
https://github.com/cloudinary/cloudinary-cli/blob/569d381562cf92974df9574947659b87f20c2efa/cloudinary_cli/modules/sync.py
Most of the logic is in the file, some small helper methods are extracted to a separate utils.
If something's not clear enough, or requires more comments/better names, please let me know.
> Refactor `sync` command

- cloudinary_cli/cli.py
- cloudinary_cli/core/search.py
- cloudinary_cli/core/uploader.py
- cloudinary_cli/core/utils.py
- cloudinary_cli/modules/make.py
- cloudinary_cli/modules/sync.py
- cloudinary_cli/modules/upload_dir.py
- cloudinary_cli/samples/__init__.py
- cloudinary_cli/templates/python/explicit
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/config_utils.py
- cloudinary_cli/utils/utils.py
- test/test_cli.py
- test/test_modules/test_cli_make.py
Fix doc strings
Fix command parameters processing
> Normalize CLI options

- cloudinary_cli/utils/utils.py
- requirements.txt
- setup.py
> Improve API documentation

- cloudinary_cli/cli.py
- cloudinary_cli/cli_group.py
- cloudinary_cli/modules/make.py
- cloudinary_cli/modules/migrate.py
- cloudinary_cli/modules/sync.py
- cloudinary_cli/modules/upload_dir.py
- cloudinary_cli/utils/utils.py
> Improve error handling of CLI commands

- cloudinary_cli/cli.py
- cloudinary_cli/cli_group.py
- cloudinary_cli/core/utils.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/utils.py
- test/test_utils.py
> Improve error handling of the API commands

- requirements.txt
- setup.py
> Bump `pycloudinary` to `1.28.1`

- cloudinary_cli/core/config.py
- cloudinary_cli/utils/config_utils.py
- test/test_cli_config.py
> Fix no configuration error message

- README.md
Provided instructions on adding your Python installation to your PATH environment variable
* No additional unit tests were required as this is a simple docs change
> Add PATH instructions (#193845)

- cloudinary_cli/modules/migrate.py
> Fix `migrate` command on Windows

- cloudinary_cli/modules/upload_dir.py
Removed condition for folders being created using upload_dir.
This is being done in conjunction with DOC-6026.  
Please don't merge this until https://github.com/CloudinaryLtd/cld_docs/pull/1768 has been approved.
> Considerations for dynamic folders

- cloudinary_cli/modules/upload_dir.py
- cloudinary_cli/utils/utils.py
- test/helper_test.py
- test/test_modules/test_cli_upload_dir.py
> Fix optional parameters handling in `upload_dir`

- cloudinary_cli/modules/upload_dir.py
- cloudinary_cli/utils/utils.py
- test/test_utils.py
> Allow passing positional parameters as optional

- requirements.txt
- setup.py
> Bump `pycloudinary` to `1.33.0`

- cloudinary_cli/core/search.py
- test/test_cli_search_api.py
> Add support for Search URL

- test/test_modules/test_cli_sync.py
> Fix flaky tests

- cloudinary_cli/modules/sync.py
- cloudinary_cli/modules/upload_dir.py
- cloudinary_cli/utils/api_utils.py
- requirements.txt
- test/helper_test.py
- test/test_modules/test_cli_sync.py
- test/test_modules/test_cli_upload_dir.py
> Add support for dynamic folders mode in `sync` and `upload_dir` commands

- cloudinary_cli/utils/api_utils.py
- requirements.txt
- test/helper_test.py
- test/test_cli_api.py
- test/test_cli_search_api.py
- test/test_modules/test_cli_sync.py
- test/test_modules/test_cli_upload_dir.py
> Fix `sync` error when `asset_folder` does not exist

- cloudinary_cli/modules/upload_dir.py
> Update `upload_dir` parameters description

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/file_utils.py
- cloudinary_cli/utils/utils.py
- test/helper_test.py
- test/test_modules/test_cli_sync.py
> Fix `sync` with duplicate `display_name` in dynamic folders mode

- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/utils.py
> Improve error messages

- cloudinary_cli/modules/sync.py
- cloudinary_cli/utils/api_utils.py
- cloudinary_cli/utils/file_utils.py
- test/test_modules/test_cli_sync.py
> Fix folder existence error in `sync` command

- cloudinary_cli/core/utils.py
> Add missing delivery types in `url` command

- Dockerfile
Add Docker file for the cloudinary-cli
Closes: https://github.com/cloudinary/cloudinary-cli/issues/25
> Docker file added

- cloudinary_cli/utils/api_utils.py
> Fix `sync` command in dynamic folder mode

- cloudinary_cli/utils/api_utils.py
> Fix duplicate `raw` files extension in `sync` command

- cloudinary_cli/templates/html/video_player
- test/test_modules/test_cli_make.py
> update video_player + add test
